# Generated by Django 5.2.8 on 2025-12-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_parametervalues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='format',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='parameter_name',
            field=models.CharField(max_length=255),
        ),
    ]
