# Generated by Django 5.2.8 on 2025-12-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_parameters_format_alter_parameters_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='parameter_name',
            field=models.CharField(max_length=200),
        ),
    ]
