# Generated by Django 5.2.8 on 2025-12-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_alter_parameters_parameter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='format',
        ),
    ]
